### ISSUE TITLE
Getting "NoMethodError: undefined method `[]' for nil:NilClass" when running "RAILS_ENV=production rails assets:precompile"

### ISSUE THREAD

**Issue by dmitrypol** [ruby-hyperloop/hyperloop#19]
- rails 5.1.4
- ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin16]
- hyperloop (0.5.8)

Following instructions http://ruby-hyperloop.org/tutorials/hyperlooprails/productionmode/ to the letter.  I have just a basic Helloworld component.  
```
applicaiton.rb:
    config.hyperloop.auto_config = false
    config.autoload_paths   -= %W(#{config.root}/app/hyperloop)
    config.eager_load_paths -= %W(#{config.root}/app/hyperloop)
    config.eager_load_paths += %W(#{config.root}/app/hyperloop/components)
    config.autoload_paths   += %W(#{config.root}/app/hyperloop/components)
production.rb
  config.assets.digest = true
  config.public_file_server.enabled = true
assets.rb
  Rails.application.config.assets.precompile += %w( react-server.js components.js )
```

Same error during Heroku deploys.  Running `rails assets:precompile` and `rails s` locally works.  Has anyone experienced this?  I would appreciate any guidance as I have been stuck on this for a long time.  

Detailed error:

```
Compiling the system assets for hyperloop-loader-system-code
rails aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Users/dmitry/.gem/ruby/2.3.5/gems/hyper-operation-0.5.12/lib/hyper-operation/call_by_class_name.rb:57:in `method_missing'
/Users/dmitry/.gem/ruby/2.3.5/gems/hyperloop-config-0.9.11/lib/hyperloop/imports.rb:105:in `compile_and_compress'
/Users/dmitry/.gem/ruby/2.3.5/gems/hyperloop-config-0.9.11/lib/hyperloop-loader-system.js.erb:1:in `_evaluate_template'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/erb_processor.rb:26:in `call'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/erb_processor.rb:13:in `call'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/dmitry/.gem/ruby/2.3.5/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/dmitry/.rubies/ruby-2.3.5/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/Users/dmitry/.gem/ruby/2.3.5/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/dmitry/.gem/ruby/2.3.5/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/dmitry/.gem/ruby/2.3.5/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/dmitry/.gem/ruby/2.3.5/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/dmitry/.gem/ruby/2.3.5/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/Users/dmitry/git/adhoc/hyper3/bin/rails:9:in `require'
/Users/dmitry/git/adhoc/hyper3/bin/rails:9:in `<top (required)>'
/Users/dmitry/.gem/ruby/2.3.5/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/dmitry/.gem/ruby/2.3.5/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/dmitry/.gem/ruby/2.3.5/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/dmitry/.gem/ruby/2.3.5/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/dmitry/.gem/ruby/2.3.5/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/dmitry/.gem/ruby/2.3.5/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/dmitry/.gem/ruby/2.3.5/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/dmitry/.rubies/ruby-2.3.5/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Users/dmitry/.rubies/ruby-2.3.5/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Users/dmitry/git/adhoc/hyper3/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => assets:precompile

```

**Comment by janbiedermann** [comment]
thanks for the report
we are in progress of preparing a new release, currently at version 1.0.0-lap20, might still take a while until final release.
Its much better, your issue is probably resolved there, give it a try, instructions here:
https://github.com/ruby-hyperloop/hyperloop/tree/1_0_0
It still has security issues though.
We are very active on gitter too :)

**Comment by dmitrypol** [comment]
Thank you, that branch worked.  I am getting this error in my log even thought I have `gem 'redis'` in my Gemfile.  

`[2018-02-12 18:49:33.368] ERROR -- Specified 'redis' for Action Cable pubsub adapter, but the gem is not loaded. Add `gem 'redis'` to your Gemfile (and ensure its version is at the minimum required by Action Cable).: nil
`

cable.yml:
```
production:
  adapter: redis
  url: redis://localhost:6379/1
```

hyperloop.rb:
```
Hyperloop.configuration do |config|
  config.transport = :action_cable
```

**Comment by catmando** [comment]
@dmitrypol can you raise a new issue, or perhaps just mention this at https://gitter.im/ruby-hyperloop/chat, as I suspect this is a config issue you are having...
