### ISSUE TITLE
Try to deploy to production with following error.

### ISSUE THREAD

**Issue by zw963** [ruby-hyperloop/hyperloop#8]
```rb
/home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/hyper-operation-0.5.11/lib/hyper-operation/call_by_class_name.rb:40:in `method_missing': undefined method `state' for Helloworld:Class (NoMethodError)
	from /home/zw963/Project/opal/hyperloop_rails51_example/app/hyperloop/components/helloworld.rb:3:in `<class:Helloworld>'
	from /home/zw963/Project/opal/hyperloop_rails51_example/app/hyperloop/components/helloworld.rb:1:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:379:in `block in require_or_load'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:36:in `block in load_interlock'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:36:in `load_interlock'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:357:in `require_or_load'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:335:in `depend_on'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:251:in `require_dependency'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/engine.rb:475:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/engine.rb:475:in `block in eager_load!'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/engine.rb:473:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/engine.rb:473:in `eager_load!'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/engine.rb:354:in `eager_load!'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/application/finisher.rb:67:in `each'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/zw963/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
	from /home/zw963/Project/opal/hyperloop_rails51_example/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:24:in `app'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/rack-2.0.3/lib/rack/server.rb:283:in `start'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:44:in `start'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:131:in `block in perform'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `tap'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `perform'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	from /home/zw963/Project/opal/hyperloop_rails51_example/bin/rails:9:in `require'
	from /home/zw963/Project/opal/hyperloop_rails51_example/bin/rails:9:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /home/zw963/.rvm/gems/ruby-2.3.4@hyperloop_rails51_example/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /home/zw963/Project/opal/hyperloop_rails51_example/bin/spring:15:in `require'
	from /home/zw963/Project/opal/hyperloop_rails51_example/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

Following is my project:  https://github.com/zw963/hyperloop_rails51_example

zw963/hyperloop_rails51_example@efc6864 is the last commit worked in development.

it just not work when try to deploy to production.

Thanks

**Comment by zw963** [comment]
could not follow up ...

close.
